name: Build and Deploy To GitHub Pages.

on:
  push:
    branches:
      - main

env:
  NODE_ENV: production
  GENERATE_SOURCEMAP: false

jobs:
  setup-build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Start
      - uses: actions/checkout@v2

      - name: Checkout
      - run: |-
          git checkout deployment

      - name: Install Dependencies
        run: |-
          npm install
        working-directory: ./

      - name: Build
        run: |-
          npm run build
          rm -r !("build"|"README.md")
          mv build/* .
          rmdir build
          cp index.html 404.html
        working-directory: ./

      - name: Deploy
        run: |-
          git add .
          git commit -m "[Automated] Deploy build"
          git push
